### ISSUE TITLE
Add a button to cancel ongoing web requests

### ISSUE THREAD

**Issue by flibber-hk** [BadMagic100/RandoSettingsManager#9]
Example implementation: Check that the string is a GUID [here](https://github.com/BadMagic100/RandoSettingsManager/blob/master/RandoSettingsManager/Menu/SettingsMenu.cs#L280)

**Comment by flibber-hk** [comment]
(Just in case I forget - if the input is being validated, it should be stripped of trailing whitespace before validation)

**Comment by BadMagic100** [comment]
Prevalidation is not an option because the implementation of the settings key may change server-side. Instead add a way to bail out of a long-running request
